name: Real-CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradlew Full Authorization
        run: chmod 777 gradlew

      - name: Test::test
        run: ./gradlew test

      - name: Clean and Build
        run: ./gradlew clean build -x test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
  CD:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradlew Full Authorization
        run: chmod 777 gradlew

      - name: Clean and Build
        run: ./gradlew clean build -x test

      - name: Create Docker Image
        run: docker build --tag saturn .

      - name: Upload to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 0816jinjin/saturn
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()